### ISSUE TITLE
Issue with code

### ISSUE THREAD

**Issue by Alanilily** [Hyricon-Development/Faliactyl#1]
/root/Faliactyl/api/oauth2.js:116
          let coins = await db.get(`coins-${userinfo.id}`) ?? 0
                                                            ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at apifiles.forEach.file (/root/Faliactyl/index.js:192:19)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/root/Faliactyl/index.js:191:10)

/root/Faliactyl/api/oauth2.js:116
          let coins = await db.get(`coins-${userinfo.id}`) ?? 0
                                                            ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at apifiles.forEach.file (/root/Faliactyl/index.js:192:19)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/root/Faliactyl/index.js:191:10)

**Comment by RianOP** [comment]
Use Nodejs 16

**Comment by RianOP** [comment]
Use Node.js 16

**Comment by Alanilily** [comment]
> Use Node.js 16

Done so i updated from node.js 12 to node.js 16 and i got a new error

/root/Faliactyl/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/root/Faliactyl/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/root/Faliactyl/node_modules/bindings/bindings.js:112:48)
    at new Database (/root/Faliactyl/node_modules/better-sqlite3/lib/database.js:48:64)
    at Database (/root/Faliactyl/node_modules/better-sqlite3/lib/database.js:11:10)
    at Object.<anonymous> (/root/Faliactyl/handlers/database.js:3:37)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'ERR_DLOPEN_FAILED'

**Comment by RianOP** [comment]
Delete old node modules and reinstall them using npm install.

**Comment by Alanilily** [comment]
> Delete old node modules and reinstall them using npm install.

Yes i did i jsut didnt notice

**Comment by Alanilily** [comment]
but i am stuck at a new part which im quite confused at

"FetchError: invalid json response body at https://panel.qloxhost.net/api/application/users?include=servers&filter[email]=veryprivateemail reason: Unexpected token < in JSON at position 0
    at /root/Faliactyl/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /root/Faliactyl/api/oauth2.js:250:35"

**Comment by RianOP** [comment]
It looks like Cloudflare is blocking your request, try allowing your dashboard IPv4 or IPv6 address.
Docs: https://developers.cloudflare.com/waf/tools/ip-access-rules/create/

**Comment by Alanilily** [comment]
Thanks, It works now.
