### ISSUE TITLE
Arc.io error

### ISSUE THREAD

**Issue by Alanilily** [Hyricon-Development/Faliactyl#2]
So im back,

ReferenceError: arciotext is not defined
    at eval (eval at <anonymous> (/root/Faliactyl/api/pages.js:74:13), <anonymous>:32:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /root/Faliactyl/api/pages.js:74:7

**Comment by RianOP** [comment]
Oh, replace the arcio.js file from the api folder with 
https://github.com/Hyricon-Development/Faliactyl/blob/main/api/arcio.js

**Comment by Alanilily** [comment]
> Oh, replace the arcio.js file from the api folder with https://github.com/Hyricon-Development/Faliactyl/blob/main/api/arcio.js

I did that Still the same error

ReferenceError: arciotext is not defined
    at eval (eval at <anonymous> (/root/client/api/pages.js:74:13), <anonymous>:32:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /root/client/api/pages.js:74:7

**Comment by Alanilily** [comment]
So after i reinstalled eveyrthing it decided to work again.
(if you find any other fix besides reinstalling everything just say it here)
