### ISSUE TITLE
arcio error 

### ISSUE THREAD

**Issue by Mrfixit935** [Hyricon-Development/Faliactyl#4]
/root/Faliactyl/api/arcio.js:8
if (settings.api.arcio.enabled == true) {
                       ^

TypeError: Cannot read properties of undefined (reading 'enabled')
    at Object.<anonymous> (/root/Faliactyl/api/arcio.js:8:24)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/Faliactyl/index.js:9:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
root@vmi939922:~/Faliactyl#

**Comment by RianOP** [comment]
Looks like you've made a mistake in settings.yml, if you need help in configuring Faliactyl, you can join our support discord server.
https://discord.gg/SntphKQCCS
