### ISSUE TITLE
new 2.1.2 bugs

### ISSUE THREAD

**Issue by Mrfixit935** [Hyricon-Development/Faliactyl#6]
1. Error: 139997868173248:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
when I log it with discord and completed the oauth2 thing it redirects me to this.

2.

[WEBSITE] An error has occured on path /servers:
Error: ENOENT: no such file or directory, open './themes/default/servers.ejs'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync [as fileLoader] (node:fs:453:35)
    at fileLoader (/root/Faliactyl/node_modules/ejs/lib/ejs.js:293:18)
    at handleCache (/root/Faliactyl/node_modules/ejs/lib/ejs.js:233:16)
    at tryHandleCache (/root/Faliactyl/node_modules/ejs/lib/ejs.js:274:16)
    at Object.exports.renderFile (/root/Faliactyl/node_modules/ejs/lib/ejs.js:491:10)
    at /root/Faliactyl/index.js:229:7
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './themes/default/servers.ejs'
}
^C

when I finish creating a server

**Comment by RianOP** [comment]
There will soon be a bug fix for this, for now you can remove /servers from your pages.yml
